[package]
name = "sos-kernel"
version = "0.1.0"
authors = [ # hacked around by
            "Hawk Weisman <hi@hawkweisman.me>"
          , # based on code by
            "Philipp Oppermann <dev@phil-opp.com>"
          ]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
spin = "0.3.4"
sos_alloc = { path = "lib/sos_alloc", features = ["buddy_as_system"] }
sos_multiboot2 = { path = "lib/sos_multiboot2" }
sos_vga = { path = "lib/sos_vga", features = ["system_term"] }

[dependencies.bitflags]
git = "https://github.com/phil-opp/bitflags.git"
branch = "no_std"

# [build-dependencies]
# nasm-rs = "^0.0.3"
